# Generated by Django 4.2.21 on 2025-06-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_membership_workspace_membership_workspace_invitation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reminder_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
